version: '2'
services:
  odoo-client:
    container_name: odoo-client
    image: odoo:14
    depends_on:
      - odoo-db-client
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo-db-client
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=postgres
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - PGHOST=odoo-db-client
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
  odoo-db-client:
    container_name: odoo-db-client
    image: postgres:12
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db_data:/var/lib/postgresql/data
volumes:
  odoo-db_data:
  odoo_data:
  odoo_addons:
