version: '3.7'

services:
  itop:
    image: vbkunin/itop
    container_name: itop
    restart: always
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=itop
      - DB_USER=itop
      - DB_PASSWORD=itop
      - ITOP_MAIL_FROM=itop@moream.org
      - ITOP_SMTP_SERVER=smtp-relay.gmail.com
      - ITOP_SMTP_PORT=25
    depends_on:
      - itop-db
    volumes:
      - ./itop_data:/var/www/html/itop/conf

  itop-db:
    image: mariadb
    container_name: itop-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
    volumes:
      - ./itop_db_data:/var/lib/mysql

  zabbix-db:
    image: postgres
    container_name: zabbix-db
    restart: always
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      TZ: Europe/Paris
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  zabbix:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix_active_agent
    depends_on:
      - zabbix-db
    ports:
      - 10051:10051
      - 10050:10050
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_DATABASE_SCHEMA: zabbix
    volumes:
      - ./zabbix-data:/var/lib/zabbix
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-server
    depends_on:
      - zabbix-db
      - zabbix
    ports:
      - 8095:8080
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix
    restart: always
  
  odoo-web:
    image: odoo:16.0
    depends_on:
      - odoo-db
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo

  odoo-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
#    environment:
#      - AGENT_HOST=itop
#      - AGENT_HOST=zabbix-web
    networks:
      - itop_network

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./heimdall-config:/config
    ports:
      - 80:80
      - 443:443
    restart: always
  
volumes:
  itop_data:
  itop_db_data:
  portainer_data:
  db-data:
  zabbix-data:

networks:
  itop_network:
