version: "3.9"

services:
  itop-client:
    image: vbkunin/itop
    container_name: itop-client
    restart: always
    ports:
      - "80:80"
    environment:
      - DB_HOST=itop-db-client
      - DB_NAME=itop
      - DB_USER=itop
      - DB_PASSWORD=itop

  itop-db-client:
    image: mariadb
    container_name: itop-db-client
    restart: always
    environment:
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
      - MYSQL_ROOT_PASSWORD=root

volumes:
  itop-db-data:

