version: "3.9"

services:
  bootstack-client:
    image: bitnami/mediawiki:latest
    container_name: bootstack-client
    restart: always
    ports:
      - "8081:8080"
    environment:
      - MEDIAWIKI_DATABASE_HOST=bootstack-db-client
      - MEDIAWIKI_DATABASE_NAME=mediawiki
      - MEDIAWIKI_DATABASE_USER=mediawiki
      - MEDIAWIKI_DATABASE_PASSWORD=mediawiki
    depends_on:
      - bootstack-db-client

  bootstack-db-client:
    image: mariadb
    container_name: bootstack-db-client
    restart: always
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./bootstack-data:/data        

volumes:
  bootstack-db-data:
  
